from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class EstimateInput(BaseModel):
    miles: float
    origin: str
    destination: str

@app.post("/estimate")
def estimate_price(data: EstimateInput):
    miles = max(data.miles, 800)
    fuelper = 0.30
    estimate = round((miles * 1.8) + (miles * fuelper), 0)

    if (data.origin == "USA" and data.destination == "CA") or \
       (data.origin == "CA" and data.destination == "USA"):
        estimate += 400

    currency = "USD" if data.origin == "USA" else "CAD"
    ppm = round(estimate / miles, 2)

    return {
        "estimate": estimate,
        "currency": currency,
        "ppm": ppm
    }
